# Site wide configuration

title: The Hamilton Lab
locale: en_US
description: part of the Arthropod Molecular Systematics Lab at the University of Idaho
logo: chris-hamilton_onblack.png
search: true
#url: http://localhost:4000
url: http://thehamiltonlab.github.io


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
plugins:
  - jekyll-remote-theme

remote_theme: "mmistakes/so-simple-theme"

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Chris Hamilton
  avatar: chris_hamilton_avatar.jpg
  email: hamiltonlab@uidaho.edu
  disqus-shortname:
  twitter: 8legs2fangs
  facebook: #username
  github: thehamiltonlab
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: #username
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: #DaveTank1
    analytics: #UA-72122602-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
